/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Entite.*;
import Gest_Ent.*;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HS-PC
 */
public class Gest_Compte_Inter extends javax.swing.JFrame {

    private static int nbCompte = 0;
    private Client client;

    /**
     * Creates new form Gest_Client
     */
    public Gest_Compte_Inter() {

        initComponents();
        this.setTitle("Gestion des comptes");
        this.setLocationRelativeTo(null);
        afficherComptes();
        lstClients();
        jMenu4.setVisible(Login.isAdmin);
    }

    public Gest_Compte_Inter(Client client) {
        initComponents();
        this.setTitle("Gestion des comptes");
        this.setLocationRelativeTo(null);
        afficherComptes();
        cmxClients.removeAllItems();
        cmxClients.addItem(client.getCin());
        this.client = client;
        jMenu4.setVisible(Login.isAdmin);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtSolde = new javax.swing.JTextField();
        btnCreer = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblComptes = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        lblNbCompte = new javax.swing.JLabel();
        cmxClients = new javax.swing.JComboBox<>();
        btnSupp = new javax.swing.JButton();
        btnLogOut = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Liste des comptes");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 35, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Solde :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(758, 195, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Client :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(758, 257, -1, -1));
        getContentPane().add(txtSolde, new org.netbeans.lib.awtextra.AbsoluteConstraints(903, 192, 147, -1));

        btnCreer.setText("Créer");
        btnCreer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreerActionPerformed(evt);
            }
        });
        getContentPane().add(btnCreer, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 313, 113, -1));

        tblComptes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Num de compte", "Date creation", "Solde", "Client"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblComptes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblComptesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblComptes);
        if (tblComptes.getColumnModel().getColumnCount() > 0) {
            tblComptes.getColumnModel().getColumn(0).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 728, 205));

        txtSearch.setToolTipText("");
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        getContentPane().add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(457, 125, 283, -1));

        lblNbCompte.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        getContentPane().add(lblNbCompte, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 127, -1, 20));

        getContentPane().add(cmxClients, new org.netbeans.lib.awtextra.AbsoluteConstraints(903, 254, 147, -1));

        btnSupp.setText("Supprimer");
        btnSupp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuppActionPerformed(evt);
            }
        });
        getContentPane().add(btnSupp, new org.netbeans.lib.awtextra.AbsoluteConstraints(789, 313, -1, -1));

        btnLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logout.png"))); // NOI18N
        btnLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogOutMouseClicked(evt);
            }
        });
        getContentPane().add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(998, 0, -1, -1));

        jMenu1.setText("Gestion des clients");
        jMenu1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Gestion des comptes");
        jMenu2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu4.setBorder(null);
        jMenu4.setText("Gestion des employés");
        jMenu4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void lstClients() {
        cmxClients.removeAllItems();
        Gest_Client gc = new Gest_Client();
        ArrayList<Client> c = gc.AfficheClients();

        for (int i = 0; i < c.size(); i++) {
            cmxClients.addItem(c.get(i).getCin());

        }
    }

    public Client client(String cin) {
        Gest_Client gc = new Gest_Client();
        return gc.AfficheClient(cin);
    }

    public void afficherComptes() {
        Gest_Compte gc = new Gest_Compte();
        ArrayList<Compte> c = gc.AfficheComptes();

        DefaultTableModel model = (DefaultTableModel) tblComptes.getModel();

        Object[] data = new Object[4];

        model.setRowCount(0);
        for (int i = 0; i < c.size(); i++) {

            data[0] = c.get(i).getNumCopte();
            data[1] = c.get(i).getDateCreation();
            data[2] = c.get(i).getSolde();
            data[3] = c.get(i).getClient().getNom() + " " + c.get(i).getClient().getPrenom();

            model.addRow(data);
        }

        lblNbCompte.setText("Nombre des comptes : " + c.size());

    }


    private void btnCreerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreerActionPerformed
        JFrame frame = new JFrame("Message");

        try {

            if (!txtSolde.getText().isEmpty() && Float.parseFloat(txtSolde.getText()) > 0) {
                if (this.client == null) {

                    this.client = client(cmxClients.getSelectedItem().toString());

                }

                Gest_Compte gc = new Gest_Compte();
                Compte compte = new Compte(Float.parseFloat(txtSolde.getText()), this.client);
                if (gc.AjouterCompte(compte)) {
                    afficherComptes();
                    lstClients();
                    JOptionPane.showMessageDialog(frame, "Ajout avec succés", "Succés", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(frame, "Une erreur se produite", "Erreur", JOptionPane.ERROR_MESSAGE);
                }

            } else {
                JOptionPane.showMessageDialog(frame, "Saisir le champ solde", "Erreur de saisir", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {

            System.out.println(e.toString());
            JOptionPane.showMessageDialog(frame, "Saisir le champ solde", "Erreur de saisir", JOptionPane.ERROR_MESSAGE);

        }

    }//GEN-LAST:event_btnCreerActionPerformed

    private void btnSuppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuppActionPerformed

        JFrame frame = new JFrame("Message");
        int numCompte = Integer.parseInt(JOptionPane.showInputDialog("Num du compte a supprimé"));

        Gest_Compte gc = new Gest_Compte();

        if (gc.SupprimerClient(numCompte)) {
            afficherComptes();
            JOptionPane.showMessageDialog(frame, "Suppression avec succés", "Succés", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(frame, "Une erreur se produite", "Erreur", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_btnSuppActionPerformed

    private void btnLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogOutMouseClicked
        Login.isAdmin = false;
        Login.code = 0;
        Login login = new Login();
        login.setVisible(true);
        dispose();

    }//GEN-LAST:event_btnLogOutMouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        Gest_Client_Inter gest_Client_Inter = new Gest_Client_Inter();
        gest_Client_Inter.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        Gest_Compte_Inter gest_Compte_Inter = new Gest_Compte_Inter();
        gest_Compte_Inter.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        Gest_Employe_Inter employe_Inter = new Gest_Employe_Inter();
        employe_Inter.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenu4MouseClicked

    private void tblComptesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblComptesMouseClicked
        try {
            DefaultTableModel model = (DefaultTableModel) tblComptes.getModel();
            int nuCompte = Integer.parseInt(model.getValueAt(tblComptes.getSelectedRow(), 0).toString());
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            Date dateCret = sdf.parse(model.getValueAt(tblComptes.getSelectedRow(), 1).toString());
            
            float solde = Float.parseFloat(model.getValueAt(tblComptes.getSelectedRow(), 2).toString());
            Compte compte = new Compte(nuCompte, dateCret, solde, client);
            
            dispose();
            Gest_Operation_Inter operation_Inter = new Gest_Operation_Inter(compte);
            operation_Inter.setVisible(true);
            } catch (Exception e) {
            System.out.println(e.toString());
        }

    }//GEN-LAST:event_tblComptesMouseClicked

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        if (!txtSearch.getText().equals("")) {

            Gest_Compte gc = new Gest_Compte();
            Compte c = gc.AfficheCompte(txtSearch.getText());

            if (c != null) {
                DefaultTableModel model = (DefaultTableModel) tblComptes.getModel();
                model.setRowCount(0);
                model = (DefaultTableModel) tblComptes.getModel();

                Object[] data = new Object[4];

                data[0] = c.getNumCopte();
                data[1] = c.getDateCreation();
                data[2] = c.getSolde();
                data[3] = c.getClient().getNom() + " " + c.getClient().getPrenom();

                model.addRow(data);

                
            } else {

                DefaultTableModel model = (DefaultTableModel) tblComptes.getModel();
                model.setRowCount(0);

            }
        }
        else{
            afficherComptes();
        }
    }//GEN-LAST:event_txtSearchKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gest_Compte_Inter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gest_Compte_Inter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gest_Compte_Inter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gest_Compte_Inter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gest_Compte_Inter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreer;
    private javax.swing.JLabel btnLogOut;
    private javax.swing.JButton btnSupp;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmxClients;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNbCompte;
    private javax.swing.JTable tblComptes;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSolde;
    // End of variables declaration//GEN-END:variables
}
