/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Entite.Client;
import Gest_Ent.Gest_Client;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HS-PC
 */
public class Gest_Client_Inter extends javax.swing.JFrame {

    private static int nbClient = 0;

    /**
     * Creates new form Gest_Client
     */
    public Gest_Client_Inter() {
        initComponents();

        this.setTitle("Gestion des clients");
        this.setLocationRelativeTo(null);

        jMenu4.setVisible(Login.isAdmin);

        radHomme.setActionCommand("Homme");
        radFemme.setActionCommand("Femme");
        afficherClients();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCin = new javax.swing.JTextField();
        txtNom = new javax.swing.JTextField();
        txtPrenom = new javax.swing.JTextField();
        txtTelphon = new javax.swing.JTextField();
        txtAdresse = new javax.swing.JTextField();
        btnAjout = new javax.swing.JButton();
        radHomme = new javax.swing.JRadioButton();
        radFemme = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClients = new javax.swing.JTable();
        btnMod = new javax.swing.JButton();
        btnSupp = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        lblNbClient = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        dteNaiss = new com.toedter.calendar.JDateChooser();
        btnLogOut = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Liste des clients");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("N° CIN :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(758, 165, 184, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("NOM :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(758, 235, 91, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Prénom :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(758, 299, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("N° Téléphone :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(758, 412, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Adresse :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(758, 478, -1, -1));

        txtCin.setToolTipText("8 chiffres");
        getContentPane().add(txtCin, new org.netbeans.lib.awtextra.AbsoluteConstraints(947, 162, 166, -1));
        getContentPane().add(txtNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(947, 232, 166, -1));
        getContentPane().add(txtPrenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(947, 296, 166, -1));
        getContentPane().add(txtTelphon, new org.netbeans.lib.awtextra.AbsoluteConstraints(947, 409, 166, -1));
        getContentPane().add(txtAdresse, new org.netbeans.lib.awtextra.AbsoluteConstraints(947, 475, 166, -1));

        btnAjout.setText("Ajouter");
        btnAjout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnAjout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 576, 87, -1));

        buttonGroup1.add(radHomme);
        radHomme.setSelected(true);
        radHomme.setText("HOMME");
        getContentPane().add(radHomme, new org.netbeans.lib.awtextra.AbsoluteConstraints(956, 530, -1, -1));

        buttonGroup1.add(radFemme);
        radFemme.setText("FEMME");
        getContentPane().add(radFemme, new org.netbeans.lib.awtextra.AbsoluteConstraints(1029, 530, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Sexe :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(758, 534, -1, -1));

        tblClients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CIN", "Nom", "Prénom", "Date naissance", "N° téléphone", "Adresse", "Sexe"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblClients.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClientsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblClients);
        if (tblClients.getColumnModel().getColumnCount() > 0) {
            tblClients.getColumnModel().getColumn(0).setResizable(false);
            tblClients.getColumnModel().getColumn(6).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 160, 728, 440));

        btnMod.setText("Modifier");
        btnMod.setEnabled(false);
        btnMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModActionPerformed(evt);
            }
        });
        getContentPane().add(btnMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(915, 576, 87, -1));

        btnSupp.setText("Supprimer");
        btnSupp.setEnabled(false);
        btnSupp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuppActionPerformed(evt);
            }
        });
        getContentPane().add(btnSupp, new org.netbeans.lib.awtextra.AbsoluteConstraints(804, 576, -1, -1));

        txtSearch.setToolTipText("");
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        getContentPane().add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 305, -1));

        lblNbClient.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        getContentPane().add(lblNbClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 119, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Date naissance :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 357, -1, -1));
        getContentPane().add(dteNaiss, new org.netbeans.lib.awtextra.AbsoluteConstraints(947, 352, 166, -1));

        btnLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logout.png"))); // NOI18N
        btnLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogOutMouseClicked(evt);
            }
        });
        getContentPane().add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 0, -1, -1));

        jMenu1.setText("Gestion des clients");
        jMenu1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Gestion des comptes");
        jMenu2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu4.setBorder(null);
        jMenu4.setText("Gestion des employés");
        jMenu4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void afficherClients() {
        Gest_Client gc = new Gest_Client();
        ArrayList<Client> c = gc.AfficheClients();

        DefaultTableModel model = (DefaultTableModel) tblClients.getModel();

        Object[] data = new Object[7];

        model.setRowCount(0);
        for (int i = 0; i < c.size(); i++) {

            data[0] = c.get(i).getCin();
            data[1] = c.get(i).getNom();
            data[2] = c.get(i).getPrenom();
            data[3] = c.get(i).getDateNaiss();
            data[4] = c.get(i).getNumTelephone();
            data[5] = c.get(i).getAdresse();
            data[6] = c.get(i).getSexe();

            model.addRow(data);
        }

        lblNbClient.setText("Nombre des clients : " + c.size());

    }


    private void btnAjoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjoutActionPerformed

        JFrame frame = new JFrame("Message");
        if (txtCin.getText().length() == 8 || txtCin.getText().equals("") || txtNom.getText().equals("") || txtPrenom.getText().equals("") || txtTelphon.getText().equals("") || txtAdresse.getText().equals("")) {

            try {

                Client client = new Client(txtCin.getText(), txtNom.getText().toUpperCase(), txtPrenom.getText(), dteNaiss.getDate(), txtTelphon.getText(), txtAdresse.getText(), buttonGroup1.getSelection().getActionCommand());

                Gest_Client gc = new Gest_Client();
                gc.AjouterClient(client);

                DefaultTableModel model = (DefaultTableModel) tblClients.getModel();
                model.setRowCount(0);

                afficherClients();

                txtCin.setText("");
                txtNom.setText("");
                txtPrenom.setText("");
                txtTelphon.setText("");
                txtAdresse.setText("");
                dteNaiss.setDate(null);

                JOptionPane.showMessageDialog(frame, client.getNom() + " " + client.getPrenom() + " est ajouté", "Succés", JOptionPane.INFORMATION_MESSAGE);
                Gest_Compte_Inter compte_Inter = new Gest_Compte_Inter(client);
                compte_Inter.setVisible(true);
                dispose();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(frame, "Probleme d'ajout", "Erreur", JOptionPane.ERROR_MESSAGE);
            }

        } else {

            JOptionPane.showMessageDialog(frame, "Les champs invalide", "Erreur ", JOptionPane.ERROR_MESSAGE);

        }


    }//GEN-LAST:event_btnAjoutActionPerformed

    private void tblClientsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClientsMouseClicked
        btnSupp.setEnabled(true);
        btnMod.setEnabled(true);

        DefaultTableModel model = (DefaultTableModel) tblClients.getModel();

        Date date;
        try {
            date = new SimpleDateFormat("yyyy-MM-dd").parse(model.getValueAt(tblClients.getSelectedRow(), 3).toString());
            dteNaiss.setDate(date);
        } catch (ParseException ex) {
            Logger.getLogger(Gest_Client_Inter.class.getName()).log(Level.SEVERE, null, ex);
        }

        txtCin.setEnabled(false);

        txtCin.setText(model.getValueAt(tblClients.getSelectedRow(), 0).toString());
        txtNom.setText(model.getValueAt(tblClients.getSelectedRow(), 1).toString());
        txtPrenom.setText(model.getValueAt(tblClients.getSelectedRow(), 2).toString());
        txtTelphon.setText(model.getValueAt(tblClients.getSelectedRow(), 4).toString());
        txtAdresse.setText(model.getValueAt(tblClients.getSelectedRow(), 5).toString());


    }//GEN-LAST:event_tblClientsMouseClicked

    private void btnSuppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuppActionPerformed

        JFrame frame = new JFrame("Message");

        try {

            Client client = new Client(txtCin.getText(), txtNom.getText().toUpperCase(), txtPrenom.getText(), new java.sql.Date(12), txtTelphon.getText(), txtAdresse.getText(), buttonGroup1.getSelection().getActionCommand());

            Gest_Client gc = new Gest_Client();

            int rep = JOptionPane.showConfirmDialog(null, "Voulez-vous vraiment supprimer " + txtNom.getText() + " " + txtPrenom.getText(), "", JOptionPane.YES_NO_CANCEL_OPTION);

            if (rep == 0) {
                gc.SupprimerClient(client);
                afficherClients();

                txtCin.setText("");
                txtNom.setText("");
                txtPrenom.setText("");
                txtTelphon.setText("");
                txtAdresse.setText("");
                txtCin.setEnabled(true);
                btnSupp.setEnabled(false);
                btnMod.setEnabled(false);

                JOptionPane.showMessageDialog(frame, client.getNom() + " " + client.getPrenom() + " est supprimé", "Succés", JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(frame, "Probleme de suppression", "Erreur", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnSuppActionPerformed

    private void btnModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModActionPerformed
        JFrame frame = new JFrame("Message");

        try {

            Client client = new Client(txtCin.getText(), txtNom.getText(), txtPrenom.getText(), dteNaiss.getDate(), txtTelphon.getText(), txtAdresse.getText(), buttonGroup1.getSelection().getActionCommand());

            Gest_Client gc = new Gest_Client();
            gc.ModiferClient(client);

            afficherClients();

            txtCin.setText("");
            txtNom.setText("");
            txtPrenom.setText("");
            txtTelphon.setText("");
            txtAdresse.setText("");
            txtCin.setEnabled(true);
            btnSupp.setEnabled(false);
            btnMod.setEnabled(false);

            JOptionPane.showMessageDialog(frame, client.getNom() + " " + client.getPrenom() + " est modifié", "Succés", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(frame, "Probleme de modification", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnModActionPerformed

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        Gest_Employe_Inter employe_Inter = new Gest_Employe_Inter();
        employe_Inter.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenu4MouseClicked

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        if (!txtSearch.getText().equals("")) {

            Gest_Client gc = new Gest_Client();
            Client c = gc.AfficheClient(txtSearch.getText());

            if (c != null) {
                DefaultTableModel model = (DefaultTableModel) tblClients.getModel();
                model.setRowCount(0);
                model = (DefaultTableModel) tblClients.getModel();

                Object[] data = new Object[7];

                data[0] = c.getCin();
                data[1] = c.getNom();
                data[2] = c.getPrenom();
                data[3] = c.getDateNaiss();
                data[4] = c.getNumTelephone();
                data[5] = c.getAdresse();
                data[6] = c.getSexe();

                model.addRow(data);

            } else {

                DefaultTableModel model = (DefaultTableModel) tblClients.getModel();
                model.setRowCount(0);

            }
        } else {
            afficherClients();
        }

    }//GEN-LAST:event_txtSearchKeyReleased

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        Gest_Compte_Inter gest_Compte_Inter = new Gest_Compte_Inter();
        gest_Compte_Inter.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenu2MouseClicked

    private void btnLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogOutMouseClicked
        Login.isAdmin = false;
        Login.code = 0;        
        Login login = new Login();
        login.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_btnLogOutMouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        Gest_Client_Inter gest_Client_Inter = new Gest_Client_Inter();
        gest_Client_Inter.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenu1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gest_Client_Inter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gest_Client_Inter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gest_Client_Inter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gest_Client_Inter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gest_Client_Inter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjout;
    private javax.swing.JLabel btnLogOut;
    private javax.swing.JButton btnMod;
    private javax.swing.JButton btnSupp;
    private javax.swing.ButtonGroup buttonGroup1;
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private com.toedter.calendar.JDateChooser dteNaiss;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNbClient;
    private javax.swing.JRadioButton radFemme;
    private javax.swing.JRadioButton radHomme;
    private javax.swing.JTable tblClients;
    private javax.swing.JTextField txtAdresse;
    private javax.swing.JTextField txtCin;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtPrenom;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTelphon;
    // End of variables declaration//GEN-END:variables
}
